#RI-4462 - add virus check for release

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -96,6 +96,11 @@ aliases:
           echo 'Found dangers'; exit 1;
         fi
 
+        if [ "$URL" == "https://download.redisinsight.redis.com/latest/RedisInsight-v2-linux-amd64.deb" ]; then
+          echo "export VIRUS_CHECK_FAILED=1" >> $BASH_ENV
+          echo 'Found dangers'; exit 1;
+        fi
+
         echo "export SKIP_VIRUSTOTAL_REPORT=true" >> $BASH_ENV
         echo 'Passed';
       shell: /bin/bash
