use upload files instead of url

diff --git a/.github/workflows/nightly-virustotal-analyze.yml b/.github/workflows/nightly-virustotal-analyze.yml
--- a/.github/workflows/nightly-virustotal-analyze.yml
+++ b/.github/workflows/nightly-virustotal-analyze.yml
@@ -18,28 +18,49 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Use File URL
-        id: file_url_check
+      - name: Download file
+        id: download_file
         run: |
           echo "Using File URL: ${{ github.event.inputs.file_url }}"
-          echo "FILE_URL=${{ github.event.inputs.file_url }}" >> $GITHUB_ENV
+          curl -sLo downloaded_file "${{ github.event.inputs.file_url }}"
+          echo "FILE_PATH=downloaded_file" >> $GITHUB_ENV
 
-      - name: Send URL to scan
+      - name: Get upload URL
+        id: get_upload_url
         run: |
-          url="${{ env.FILE_URL }}"
-          echo "URL to check: $url"
+          # Request an upload URL for large files
+          # Reference: https://docs.virustotal.com/reference/files-scan
 
-          # Upload the URL to VirusTotal
-          analysedId=$(curl -sq -XPOST https://www.virustotal.com/api/v3/urls \
-            -H "x-apikey: $VIRUSTOTAL_API_KEY" \
-            --form url=${url} | jq -r '.data.id')
+          uploadUrl=$(curl -sq -XGET https://www.virustotal.com/api/v3/files/upload_url \
+            -H "x-apikey: $VIRUSTOTAL_API_KEY" | jq -r '.data')
 
-          if [ "$analysedId" == "null" ]; then
-            echo 'Status is null, something went wrong';
-            exit 1;
+          if [ -z "$uploadUrl" ] || [ "$uploadUrl" == "null" ]; then
+            echo 'Failed to retrieve upload URL from VirusTotal'
+            exit 1
           fi
 
-          echo "ANALYZED_ID=$analysedId" >> $GITHUB_ENV
+          echo "UPLOAD_URL=$uploadUrl" >> $GITHUB_ENV
+
+      - name: Upload large file to VirusTotal
+        id: upload_large_file
+        run: |
+          file_path="${{ env.FILE_PATH }}"
+          upload_url="${{ env.UPLOAD_URL }}"
+          echo "Uploading file: $file_path to VirusTotal using upload URL"
+
+          # Upload the file to the provided upload URL
+          # Reference: https://docs.virustotal.com/reference/files-upload-url
+
+          analyzedId=$(curl -sq -XPOST "$upload_url" \
+            -H "x-apikey: $VIRUSTOTAL_API_KEY" \
+            --form "file=@${file_path}" | jq -r '.data.id')
+
+          if [ "$analyzedId" == "null" ]; then
+            echo 'File upload failed, something went wrong'
+            exit 1
+          fi
+
+          echo "ANALYZED_ID=$analyzedId" >> $GITHUB_ENV
 
       - name: Check analyze status
         run: |
